### ISSUE TITLE
Windows build failing

### ISSUE THREAD

**Issue by maretodoric** [phenobarbital/asyncdb#468]
Hello,

is this one supported on Windows by any chance? Build is failing.

```
python -m pip install asyncdb
Collecting asyncdb
  Using cached asyncdb-2.1.40.tar.gz (228 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [21 lines of output]
      Traceback (most recent call last):
        File "C:\Users\user\Desktop\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 351, in <module>
          main()
        File "C:\Users\user\Desktop\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 333, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
        File "C:\Users\user\Desktop\Programs\Python\Python310\lib\site-packages\pip\_vendor\pep517\in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-ik_estk3\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-ik_estk3\overlay\Lib\site-packages\setuptools\build_meta.py", line 320, in _get_build_requires
          self.run_setup()
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-ik_estk3\overlay\Lib\site-packages\setuptools\build_meta.py", line 335, in run_setup
          exec(code, locals())
        File "<string>", line 270, in <module>
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-ik_estk3\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 970, in cythonize
          module_list, module_metadata = create_extension_list(
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-ik_estk3\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 816, in create_extension_list
          for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
        File "C:\Users\user\AppData\Local\Temp\pip-build-env-ik_estk3\overlay\Lib\site-packages\Cython\Build\Dependencies.py", line 114, in nonempty
          raise ValueError(error_msg)
      ValueError: 'asyncdb/exceptions/exceptions.pyx' doesn't match any files
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
```

It's a Windows 10 with Python 3.10

**Comment by panos-stavrianos** [comment]
I experience the same problem, any suggestions?

**Comment by tahakara** [comment]
same problem 
pip 23.2.1
Python 3.11.4
X64 Windows11

**Comment by phenobarbital** [comment]
Long story short:
Hi, the primary issue is that I'm not using Windows, and my GitHub workflow is tightly integrated with Ubuntu builds, I can add builds for Windows but I don't have OS for testing.

AsyncDB has some sub-packages in Cython and needs some compilation tools, if you try to install it in a different operating system you should install a compiler.

I added a Job to build Windows wheels, but I haven't tested it yet.
